

public enum UserStatus {
	
    COMPLIENT,
    IN_BREACH_OF_CONTRACT,
    PRIVELEGES_SUSPENDED_1D,
    PRIVELEGES_SUSPENDED_3D,
    PRIVELEGES_SUSPENDED_10D,
    PRIVELEGES_SUSPENDED_30D,
    PRIVELEGES_SUSPENDED_180D,
    PRIVELEGES_REVOKED
    
    
    //TODO --- POSSIBLY PUT SUSPENSION LOGIC IN HERE AS WELL...
    
    
}